const express = require("express");
const cors = require("cors");
const nodemailer = require("nodemailer");
const bodyParser = require("body-parser");

env = require("dotenv").config();

const app = express();
const PORT = 5000;

app.use(cors());
app.use(bodyParser.json());

// Nodemailer transporter setup
const transporter = nodemailer.createTransport({
  service: "gmail",
  auth: {
    user: process.env.EMAIL, // Your email
    pass: process.env.PASSWORD, // Your email password or App Password
  },
});

app.post("/send-email", async (req, res) => {
  const { Name, Mobile, Email, Subject, Message } = req.body;

  if (!Name || !Mobile || !Email || !Subject || !Message) {
    return res.status(400).json({ error: "All fields are required." });
  }

  const adminMailOptions = {
    from: process.env.EMAIL,
    to: process.env.ADMIN_EMAIL, // Your email to receive form details
    subject: `📩 New Contact Form Submission – ${Subject}`,
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; padding: 20px; border: 1px solid #ddd; border-radius: 8px;">
        <h2 style="color: #E91E63; text-align: center;">New Contact Form Submission</h2>
        <p><strong>📌 Subject:</strong> ${Subject}</p>
        <p><strong>👤 Name:</strong> ${Name}</p>
        <p><strong>📞 Mobile:</strong> ${Mobile}</p>
        <p><strong>✉️ Email:</strong> <a href="mailto:${Email}">${Email}</a></p>
        <p><strong>📝 Message:</strong></p>
        <blockquote style="background: #f9f9f9; padding: 15px; border-left: 4px solid #E91E63; border-radius: 5px;">${Message}</blockquote>
        <p style="margin-top: 20px;">Please review and respond promptly.</p>
        <hr style="border: none; border-top: 1px solid #ddd;" />
        <p style="font-size: 12px; color: #777;">This email was automatically generated by the Love for Pride Unity contact form.</p>
      </div>
    `,
  };
  

  // const userMailOptions = {
  //   from: process.env.EMAIL,
  //   to: Email,
  //   subject: "🌈 Confirmation: We Received Your Message!",
  //   html: `
  //     <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; padding: 20px; border: 1px solid #ddd; border-radius: 8px;">
  //       <h2 style="color: #E91E63; text-align: center;">Thank You for Reaching Out! 🌟</h2>
  //       <p>Dear <strong>${Name}</strong>,</p>
  //       <p>We appreciate you taking the time to connect with <strong>Love for Pride Unity</strong>. Your message has been received, and our team will get back to you as soon as possible.</p>
  //       <p>In the meantime, feel free to explore more about our initiatives, events, and ways to get involved.</p>
  //       <p style="margin-top: 20px;">With love and unity,</p>
  //       <p><strong>Love for Pride Unity Team</strong></p>
  //       <hr style="border: none; border-top: 1px solid #ddd;" />
  //       <p style="font-size: 12px; color: #777;">For inquiries, contact us at <a href="mailto:loveforprideunity@gmail.com">loveforprideunity@gmail.com</a></p>
  //     </div>
  //   `,
  // };
  

  const userMailOptions = {
    from: process.env.EMAIL,
    to: Email,
    subject: "🌈 Confirmation: We Received Your Message!",
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; padding: 20px; border: 1px solid #ddd; border-radius: 8px;">
        <div style="text-align: center; margin-bottom: 20px;">
          <img src="https://your-logo-url.com/logo.png" alt="Love for Pride Unity" style="max-width: 150px;">
        </div>
        <h2 style="color: #E91E63; text-align: center;">Thank You for Reaching Out! 🌟</h2>
        <p>Dear <strong>${Name}</strong>,</p>
        <p>We appreciate you taking the time to connect with <strong>Love for Pride Unity</strong>. Your message has been received, and our team will get back to you as soon as possible.</p>
        <p>In the meantime, feel free to explore more about our initiatives, events, and ways to get involved.</p>
        <p style="margin-top: 20px;">With love and unity,</p>
        <p><strong>Love for Pride Unity Team</strong></p>
        <hr style="border: none; border-top: 1px solid #ddd;" />
        <p style="font-size: 12px; color: #777;">For inquiries, contact us at <a href="mailto:loveforprideunity@gmail.com">loveforprideunity@gmail.com</a></p>
      </div>
    `,
};



  try {
    await transporter.sendMail(adminMailOptions);
    await transporter.sendMail(userMailOptions);
    res.status(200).json({ message: "Emails sent successfully!" });
  } catch (error) {
    console.error("Error sending email:", error);
    res.status(500).json({ error: "Failed to send email." });
  }
});

app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});
